### ISSUE TITLE
punchcard stylesheets need to specify div

### ISSUE THREAD

**Issue by jspaaks** [nlesc-sherlock/punchcardjs#19]
**Expected behavior**

css class style should be defined for a `div`, not just a random dom element.

**Actual behavior**

currently, the css may say for example 

``` css
/* the top level div */
.punchcard-date-circle {
    height: 600px;
}

```

but this means that when you define, say a `<table>` element with `<table class="punchcard-date-circle">`, you'll get unexpected behavior.

**Steps to reproduce the behavior**
add `div to the class`, as in 

``` css
/* the top level div */
div.punchcard-date-circle {
    height: 600px;
}
```
